### ISSUE TITLE
wish:  a shell

### ISSUE THREAD

**Issue by stappersg** [rust-console/rrt0#6]
Hi,

This issue is for asking about a _shell_.   With _shell_ I do mean a programma that can start other programms. It would be the programma that `rrt0` starts.

What the _shell_ does:
* Showing a _"prompt"_
* Scanning buttons
* When _"next"_ button is pressed, it shows _filename of next programm_
* When _"enter"_ button is pressed, it starts selected programm_
* At _"selected programm exit"_ back to begin,  prompting & scanning

No need for recreating an Operating System, just something that makes it possible to have multiple programms on a _console device_ waiting to be started. Programms / Games that are indepently (developped).

**Comment by parasyte** [comment]
That does not fit the goals of this crate, since it doesn't do any initialization beyond configuring a runtime environment for Rust.

Even something simple like showing text on the screen is pushed to a higher abstraction layer like [`n64lib`](https://github.com/rust-console/rrt0/tree/main/examples/n64lib). (I will probably be renaming that crate and publishing it separately, FWIW.)

It sounds like what you are talking about is more bootloader oriented. `rrt0` is runtime oriented.

**Comment by stappersg** [comment]
Acknowledge on _"That does not fit the goals of this crate"_.

Advice on a _"runtime invoker of  other code"_  a.k.a. _"shell"_  still welcome.   (And feel free to close this issue without further explanation.)

**Comment by parasyte** [comment]
What are your specifications for a "shell"?

- Does it need to load programs from external memory? If so, what kinds of external memory? Some example of external memory are the N64 cartridge ROM, SD card, CF, card, USB thumb drive, etc.
- What file formats should it support? ELF object files, ROM files, or plain binaries plus other necessary metadata?
- What file systems should be supported? FAT32 is usually the default, but an application-specific internal file system may also be adequate.

**Comment by stappersg** [comment]
:smiley: 
I'm here as bagger, not as chooser. 
I haven't thought that far, just asking if a _"shell"_ exists for _rust console_. 
:smiley: 

Euh yes, the _shell_ will need to know which programs are available for getting started.  I can't provide specifications, sorry.  I did find https://github.com/rust-embedded-community/embedded-storage I don't know if that is any help.

**Comment by parasyte** [comment]
I think I see where you are coming from. I don't know of any examples of a _general purpose_ shell (if we continue to use this terminology for clarity). Most are going to be specific to a console (cf. Homebrew Channel for Wii vs Homebrew Launcher for 3DS) or to a flash cart (EverDrive 64 vs 64Drive). In the former example the Wii and 3DS loaders are completely different. In the latter case both cartridges have their own multi-stage loader solution, and they are not compatible with each other.

One way to visualize how runtime environment initialization like `rrt0` differs from a shell is that all programs will need runtime environment initialization, including the shell itself. At a bare minimum, this means configuring the stack pointer so that functions can be called. See https://en.wikipedia.org/wiki/Crt0 for the analogous initialization stages for programs written in C.

The closest thing I know of to a general purpose bootloader would be something like [barebox](https://www.barebox.org/). But it would have to be ported to N64. Since this request is unrelated to this crate, I'll close it. But hopefully I have been able to help guide you in the right direction.

**Comment by stappersg** [comment]
Thanks

My quest continues at https://jhbruhn.de/posts/moonboot/ An OTA Bootloader Construction Framework for Rust no_std environments. 


Regards
Geert Stappers
